### ISSUE TITLE
play-url not working with age-restricted YT videos

### ISSUE THREAD

**Issue by Konfirm44** [kmolski/acme-bot#2]
Error: No tracks found for the provided URL list!.

please fix

**Comment by kmolski** [comment]
got it boss

**Comment by kmolski** [comment]
The latest version of `youtube-dl` does not fix this problem. However, an actively maintained fork called [yt-dlp](https://github.com/yt-dlp/yt-dlp) seems to work. After replacing the dependency, age-restricted videos play correctly. I've also taken the opportunity to migrate the project from Pipenv to Poetry.
